name: Run Unit Tests
run-name: Coverage 🧪
"on": push
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm install
            
              npm run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      
