name: Deploy to One.com
run-name: Deploy to One.com 🚀
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build Vue.js project
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to One.com
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.we-lander.dk
        username: we-lander.dk
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: /dist/
        remote-dir: /nordbor