name: Deploy to One.com
run-name: Deploy to One.com 🚀
on:
  push:
    branches:
      - develop

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.we-lander.dk
        username: we-lander.dk
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        remote-dir: /nordbor