name: Qodana Scan

on:
  push:
    branches:
      - qodana
  pull_request:

jobs:
  qodana-scan:
    runs-on: ubuntu-latest
    name: Run Qodana Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA }}

        exclude:
          - name: Eslint
          - name: CommaExpressionJS

